# PROJECT : Churn Classification Modelling

`WORK IN PROGRESS`

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

%matplotlib inline

In [2]:
df = pd.read_csv("./dataset/churn.csv")

In [3]:
df.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           3333 non-null   object
 1   Account Length  3333 non-null   int64
 2   Area Code       3333 non-null   int64
 3   Phone           3333 non-null   object
 4   Int'l Plan      3333 non-null   object
 5   VMail Plan      3333 non-null   object
 6   VMail Message   3333 non-null   int64
 7   Day Mins        3333 non-null   float64
 8   Day Calls       3333 non-null   int64
 9   Day Charge      3333 non-null   float64
 10  Eve Mins        3333 non-null   float64
 11  Eve Calls       3333 non-null   int64
 12  Eve Charge      3333 non-null   float64
 13  Night Mins      3333 non-null   float64
 14  Night Calls     3333 non-null   int64
 15  Night Charge    3333 non-null   float64
 16  Intl Mins       3333 non-null   float64
 17  Intl Calls      3333 non-null   int64
 18  Intl Charge     3333 non-null   float64
 19  CustServ Calls  3333 non-null   int64
 20  Churn?          3333 non-null   object
dtypes: float64(8), int64(8), object(5)
memory usage: 546.9+ KB

In [5]:
df.describe()

,Account Length,Area Code,VMail Message,Day Mins,Day Calls,Day Charge,Eve Mins,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,437.182418,8.099010,179.775098,100.435644,30.562307,200.980348,100.114311,17.083540,200.872037,100.107711,9.039325,10.237294,4.479448,2.764581,1.562856
std,39.822106,42.371290,13.688365,54.467389,20.069084,9.259435,50.713844,19.922625,4.310668,50.573847,19.568609,2.275873,2.791840,2.461214,0.753773,1.315491
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.430000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.400000,114.000000,36.790000,235.300000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [6]:
targetMatrix = df['Churn?']

In [7]:
targetMatrix.value_counts()

False.    2850
True.      483
Name: Churn?, dtype: int64

In [8]:
df.columns

Index(['State', 'Account Length', 'Area Code', 'Phone', 'Int'l Plan',
       'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls', 'Day Charge',
       'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins', 'Night Calls',
       'Night Charge', 'Intl Mins', 'Intl Calls', 'Intl Charge',
       'CustServ Calls', 'Churn?'],
      dtype='object')

In [42]:
featureMatrix = df.drop(['Phone','Churn?'],axis=1)

In [43]:
featureMatrix[['Int\'l Plan','VMail Plan']] = featureMatrix[['Int\'l Plan','VMail Plan'] ]== 'yes'

In [44]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

oheFit = ohe.fit(featureMatrix['State'].values.reshape(-1,1))

oheResult = oheFit.transform(featureMatrix['State'].values.reshape(-1,1)).toarray()

stateDf = pd.DataFrame(oheResult,columns=oheFit.get_feature_names())

In [45]:
featureMatrix = featureMatrix.drop(['State'],axis=1)

In [47]:
featureMatrix = featureMatrix.join(stateDf)

In [48]:
featureMatrix

,Account Length,Area Code,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,Eve Mins,Eve Calls,...,x0_SD,x0_TN,x0_TX,x0_UT,x0_VA,x0_VT,x0_WA,x0_WI,x0_WV,x0_WY
0,128,415,False,True,25,265.1,110,45.07,197.4,99,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,107,415,False,True,26,161.6,123,27.47,195.5,103,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,137,415,False,False,0,243.4,114,41.38,121.2,110,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,84,408,True,False,0,299.4,71,50.90,61.9,88,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,75,415,True,False,0,166.7,113,28.34,148.3,122,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,192,415,False,True,36,156.2,77,26.55,215.5,126,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3329,68,415,False,False,0,231.1,57,39.29,153.4,55,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3330,28,510,False,False,0,180.8,109,30.74,288.8,58,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3331,184,510,True,False,0,213.8,105,36.35,159.6,84,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3332,74,415,False,True,25,234.4,113,39.85,265.9,82,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
from sklearn.impute import SimpleImputer
#Missing values replaced by mean
imputer =SimpleImputer(missing_values=np.nan,strategy='mean',fill_value=None,verbose=0,copy=True)
#Fit to data, then transform it.
imputerFit = imputer.fit(featureMatrix)
featureMatrix = imputerFit.transform(featureMatrix)

In [50]:
featureMatrix

array([[128., 415.,   0., ...,   0.,   0.,   0.],
       [107., 415.,   0., ...,   0.,   0.,   0.],
       [137., 415.,   0., ...,   0.,   0.,   0.],
       ...,
       [ 28., 510.,   0., ...,   0.,   0.,   0.],
       [184., 510.,   1., ...,   0.,   0.,   0.],
       [ 74., 415.,   0., ...,   0.,   0.,   0.]])

In [51]:
from sklearn.preprocessing import StandardScaler
#Standardize the data by removing the mean and scaling to unit variance
scaler = StandardScaler()
#Fit to data, then transform it.
scalerFit = scaler.fit(featureMatrix)

featureMatrix = scalerFit.transform(featureMatrix)

In [52]:
featureMatrix

array([[ 0.67648946, -0.52360328, -0.32758048, ..., -0.1548003 ,
        -0.18123975, -0.15378117],
       [ 0.14906505, -0.52360328, -0.32758048, ..., -0.1548003 ,
        -0.18123975, -0.15378117],
       [ 0.9025285 , -0.52360328, -0.32758048, ..., -0.1548003 ,
        -0.18123975, -0.15378117],
       ...,
       [-1.83505538,  1.71881732, -0.32758048, ..., -0.1548003 ,
        -0.18123975, -0.15378117],
       [ 2.08295458,  1.71881732,  3.05268496, ..., -0.1548003 ,
        -0.18123975, -0.15378117],
       [-0.67974475, -0.52360328, -0.32758048, ..., -0.1548003 ,
        -0.18123975, -0.15378117]])

In [56]:
seed = 42

from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain,yTest = train_test_split(featureMatrix,targetMatrix,test_size=0.1,random_state=seed)

## Decision Tree Classification

In [76]:
from sklearn.tree import DecisionTreeClassifier

dtClassifier = DecisionTreeClassifier(random_state=seed)

dtModel = dtClassifier.fit(xTrain,yTrain)

yPredictDT = dtModel.predict(xTest)

dtScore = dtClassifier.score(xTest,yTest)
print("Decision Tree Score :",dtScore)

Decision Tree Score : 0.9101796407185628

## Gaussian Naive Bayes

In [85]:
from sklearn.naive_bayes import GaussianNB

gnbClassifier = GaussianNB()

gnbModel = gnbClassifier.fit(xTrain,yTrain)

yPredictGNB = gnbModel.predict(xTest)

gnbScore = gnbModel.score(xTest,yTest)

print("Gaussian Naive Bayes Score :",gnbScore)

Gaussian Naive Bayes Score : 0.6287425149700598

## Stochastic Gradient Descent

In [108]:
from sklearn.linear_model import SGDClassifier

sgdClassifier = SGDClassifier(loss='modified_huber', shuffle=True,random_state=seed)

sgdModel = sgdClassifier.fit(xTrain,yTrain)

yPredictSGD = sgdModel.score(xTest,yTest)

sgdScore = sgdModel.score(xTest,yTest)
print("Stochastic Gradient Descent Classification score :",sgdScore)

Stochastic Gradient Descent Classification score : 0.8023952095808383

## Support Vector Machine

In [109]:
from sklearn.svm import SVC

svClassifier = SVC(kernel="linear", C=0.025,random_state=seed)
svModel = svClassifier.fit(xTrain, yTrain)
yPredictSV = svClassifier.predict(xTest)

svScore = svClassifier.score(xTest, yTest)
print('SVM Classifier : ',svScore)

SVM Classifier :  0.8383233532934131

## Random Forest

In [110]:
from sklearn.ensemble import RandomForestClassifier
rfClassifier = RandomForestClassifier(max_depth=5, n_estimators=10, max_features=10,random_state=seed)
rfModel = rfClassifier.fit(xTrain, yTrain)
yPredictRF = rfClassifier.predict(xTest)
rfScore = rfClassifier.score(xTest, yTest)
print('Random Forest Classifier : ',rfScore)

Random Forest Classifier :  0.874251497005988

## Random Forest (Parameter Tuning)

In [111]:
from sklearn.ensemble import RandomForestClassifier
rfClassifier = RandomForestClassifier(max_depth=5, n_estimators=15, max_features=60,random_state=seed)
rfModel = rfClassifier.fit(xTrain, yTrain)
yPredictRF = rfClassifier.predict(xTest)
rfScore = rfClassifier.score(xTest, yTest)
print('Random Forest Classifier : ',rfScore)

Random Forest Classifier :  0.9431137724550899

## Imbalance in target classes 

- Some classification problems can exhibit a large imbalance in the distribution of the target classes.
- for instance there could be several times more negative samples than positive samples. In such cases it is recommended to use stratified sampling as implemented in StratifiedKFold and StratifiedShuffleSplit to ensure that relative class frequencies is approximately preserved in each train and validation fold.

In [112]:
from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits=1,test_size=0.1,random_state=7)
sss.get_n_splits(featureMatrix,targetMatrix)

print(sss)

StratifiedShuffleSplit(n_splits=1, random_state=7, test_size=0.1,
            train_size=None)

In [121]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC,LinearSVC
from sklearn.multiclass import OneVsRestClassifier


classifiers = [
    DecisionTreeClassifier(),
    GaussianNB(),
    SGDClassifier(loss='modified_huber', shuffle=True),
    SVC(kernel="linear", C=0.025),
    KNeighborsClassifier(),
    OneVsRestClassifier(LinearSVC()),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=10),
    AdaBoostClassifier(),
   ]
for clf in classifiers:
    score=0
    for train_index, test_index in sss.split(featureMatrix,targetMatrix):
        X_train, X_test = featureMatrix[train_index], featureMatrix[test_index]
        y_train, y_test = targetMatrix[train_index], targetMatrix[test_index]
        clf.fit(X_train, y_train)
        score=score+clf.score(X_test, y_test)
    print(clf,score)

DecisionTreeClassifier() 0.8862275449101796
GaussianNB() 0.6137724550898204
SGDClassifier(loss='modified_huber') 0.7784431137724551
SVC(C=0.025, kernel='linear') 0.8562874251497006
KNeighborsClassifier() 0.8592814371257484

/home/nishant/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "

OneVsRestClassifier(estimator=LinearSVC()) 0.8652694610778443
RandomForestClassifier(max_depth=5, max_features=10, n_estimators=10) 0.8862275449101796
AdaBoostClassifier() 0.8832335329341318